### ISSUE TITLE
DPI in game lobby - change map, start game buttons missing

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-client#18] opened 2015-08-04 18:53 UTC
DPI related?

**Comment by Rampastring** [comment] 2015-08-20 13:22
Apparently not DPI related after all. Need to add some additional logging so I can see what's the cause.

**Comment by Rampastring** [comment] 2015-09-16 14:40
Should be fixed in client version 1.19.

**Closed by Rampastring** 2015-09-16 14:40 UTC
Labels: bug
